nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: [ 'http://localhost:4200' ]
    allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
    allow_headers: [ '*' ]
    max_age: 3600
  paths:
    '^/api/':
      allow_origin: [ 'http://localhost:4200' ]
      allow_headers: [ '*' ]
      allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE', 'OPTION' ]
      max_age: 3600